{
  "error": "Failed to generate JSON output, exception 'NoneType' object has no attribute 'to_json'\nTraceback (most recent call last):\n  File \"/Users/daveih/Documents/python/usdm/src/usdm_db/__init__.py\", line 62, in to_json\n    raw_json = self._wrapper.to_json()\nAttributeError: 'NoneType' object has no attribute 'to_json'\n"
}